#!/usr/bin/env python3
"""Embed the MECC Oregon Trail art (PNG, kept compressed) as C arrays.

    tools/gen_assets.py <path-to-OregonTrail-repo>

Writes src/art/gen/*.{h,cpp}. LovyanGFX decodes the PNGs from flash at runtime.
On ESP32 a plain `const` array is memory-mapped in flash, so no PROGMEM needed.
"""
import os
import sys

REPO = sys.argv[1] if len(sys.argv) > 1 else "."
ART = os.path.join(REPO, "src/OregonTrailDotNet.Assets/Resources/art")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "art", "gen")

# group -> list of (symbol, relative png path)
GROUPS = {
    "landmarks": [(f"lm_{i}", f"landmarks/p{i}.png") for i in range(18)],
    "wagon":     [(f"wagon_{i}", f"sprites/travelox/{i:02d}.png") for i in range(1, 6)],
    "hunter":    [(f"hunter_{i}", f"sprites/hunter/{i:02d}.png") for i in range(1, 25)],
    "animals":   [(f"animal_{i}", f"sprites/animals/{i:02d}.png") for i in range(1, 49)],
    "raft":      [(f"raft_{i}", f"sprites/float/{i:02d}.png") for i in range(1, 10)],
    "terrain":   [(f"terr_{i}", f"sprites/terrain/{i:02d}.png") for i in range(1, 15)],
    "scenery":   [(f"scen_{i}", f"sprites/scenery/{i:02d}.png") for i in range(1, 18)],
    "events":    [(f"evt_{i}", f"sprites/events/{i:02d}.png") for i in range(1, 8)],
    "misc":      [("map_img", "map.png"), ("family_img", "family.png"),
                  ("banner_img", "banner.png"), ("tomb_img", "tombstone.png")],
}


def emit(group, entries):
    hpath = os.path.join(OUT, f"{group}.h")
    cpath = os.path.join(OUT, f"{group}.cpp")
    with open(hpath, "w") as h:
        h.write(f"// Generated by tools/gen_assets.py — do not edit.\n#pragma once\n")
        h.write("#include <stdint.h>\n#include <stddef.h>\n\nnamespace art {\n")
        for sym, _ in entries:
            h.write(f"extern const uint8_t {sym}[];\nextern const size_t {sym}_len;\n")
        h.write("}  // namespace art\n")

    total = 0
    with open(cpath, "w") as c:
        c.write(f'// Generated by tools/gen_assets.py — do not edit.\n#include "art/gen/{group}.h"\n\n')
        c.write("namespace art {\n")
        for sym, rel in entries:
            data = open(os.path.join(ART, rel), "rb").read()
            total += len(data)
            c.write(f"const uint8_t {sym}[] = {{")
            c.write(",".join(str(b) for b in data))
            c.write(f"}};\nconst size_t {sym}_len = {len(data)};\n\n")
        c.write("}  // namespace art\n")
    print(f"  {group}: {len(entries)} images, {total:,} bytes")


def main():
    os.makedirs(OUT, exist_ok=True)
    grand = 0
    for group, entries in GROUPS.items():
        emit(group, entries)
    print("done — src/art/gen/")


if __name__ == "__main__":
    main()
