#!/usr/bin/env python3
"""Embed the MECC Oregon Trail art (PNG, kept compressed) and music as C arrays.

    tools/gen_assets.py <path-to-OregonTrail-repo>

Writes src/art/gen/*.{h,cpp}. LovyanGFX decodes the PNGs from flash at runtime.
On ESP32 a plain `const` array is memory-mapped in flash, so no PROGMEM needed.
Music comes from Resources/music/*.json — each has a pre-decoded `events` list of
{hz, ms} which drops straight into audio::playSong().
"""
import json
import os
import sys

REPO = sys.argv[1] if len(sys.argv) > 1 else "."
ART = os.path.join(REPO, "src/OregonTrailDotNet.Assets/Resources/art")
MUSIC = os.path.join(REPO, "src/OregonTrailDotNet.Assets/Resources/music")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "art", "gen")

# group -> list of (symbol, relative png path)
GROUPS = {
    "landmarks": [(f"lm_{i}", f"landmarks/p{i}.png") for i in range(18)],
    "wagon":     [(f"wagon_{i}", f"sprites/travelox/{i:02d}.png") for i in range(1, 6)],
    "hunter":    [(f"hunter_{i}", f"sprites/hunter/{i:02d}.png") for i in range(1, 25)],
    "animals":   [(f"animal_{i}", f"sprites/animals/{i:02d}.png") for i in range(1, 49)],
    "raft":      [(f"raft_{i}", f"sprites/float/{i:02d}.png") for i in range(1, 10)],
    "terrain":   [(f"terr_{i}", f"sprites/terrain/{i:02d}.png") for i in range(1, 15)],
    "scenery":   [(f"scen_{i}", f"sprites/scenery/{i:02d}.png") for i in range(1, 18)],
    "events":    [(f"evt_{i}", f"sprites/events/{i:02d}.png") for i in range(1, 8)],
    "misc":      [("map_img", "map.png"), ("family_img", "family.png"),
                  ("banner_img", "banner.png"), ("tomb_img", "tombstone.png")],
}


def emit(group, entries):
    hpath = os.path.join(OUT, f"{group}.h")
    cpath = os.path.join(OUT, f"{group}.cpp")
    with open(hpath, "w") as h:
        h.write(f"// Generated by tools/gen_assets.py — do not edit.\n#pragma once\n")
        h.write("#include <stdint.h>\n#include <stddef.h>\n\nnamespace art {\n")
        for sym, _ in entries:
            h.write(f"extern const uint8_t {sym}[];\nextern const size_t {sym}_len;\n")
        h.write("}  // namespace art\n")

    total = 0
    with open(cpath, "w") as c:
        c.write(f'// Generated by tools/gen_assets.py — do not edit.\n#include "art/gen/{group}.h"\n\n')
        c.write("namespace art {\n")
        for sym, rel in entries:
            data = open(os.path.join(ART, rel), "rb").read()
            total += len(data)
            c.write(f"const uint8_t {sym}[] = {{")
            c.write(",".join(str(b) for b in data))
            c.write(f"}};\nconst size_t {sym}_len = {len(data)};\n\n")
        c.write("}  // namespace art\n")
    print(f"  {group}: {len(entries)} images, {total:,} bytes")


def emit_music():
    """music/landmarks/NN-*.json (index 0..17) + music/tombstone.json ->
    src/art/gen/music.{h,cpp} as audio::Note tables."""
    files = sorted(f for f in os.listdir(os.path.join(MUSIC, "landmarks"))
                   if f.endswith(".json"))
    songs = [("lm%d" % i, os.path.join("landmarks", f)) for i, f in enumerate(files)]
    songs.append(("tomb", "tombstone.json"))

    def notes(rel):
        j = json.load(open(os.path.join(MUSIC, rel)))
        out = []
        for e in j.get("events", []):
            hz = int(round(e.get("hz") or 0))
            ms = int(round(e.get("ms") or 0))
            out.append((min(hz, 65535), min(ms, 65535)))
        return out

    with open(os.path.join(OUT, "music.h"), "w") as h:
        h.write("// Generated by tools/gen_assets.py — do not edit.\n#pragma once\n")
        h.write('#include <stddef.h>\n#include "hw/Audio.h"\n\n')
        h.write("namespace music {\n")
        h.write("struct Song { const audio::Note* notes; size_t len; };\n")
        h.write("extern const Song landmark[%d];\n" % (len(songs) - 1))
        h.write("extern const Song tombstone;\n")
        h.write("}  // namespace music\n")

    total = 0
    with open(os.path.join(OUT, "music.cpp"), "w") as c:
        c.write('// Generated by tools/gen_assets.py — do not edit.\n')
        c.write('#include "art/gen/music.h"\n\nnamespace music {\n')
        for sym, rel in songs:
            ns = notes(rel)
            total += len(ns)
            c.write("static const audio::Note %s[] = {" % sym)
            c.write(",".join("{%d,%d}" % (hz, ms) for hz, ms in ns))
            c.write("};\n")
        c.write("\nconst Song landmark[%d] = {" % (len(songs) - 1))
        c.write(",".join("{%s,sizeof(%s)/sizeof(%s[0])}" % (s, s, s)
                         for s, _ in songs[:-1]))
        c.write("};\n")
        c.write("const Song tombstone = {tomb, sizeof(tomb)/sizeof(tomb[0])};\n")
        c.write("}  // namespace music\n")
    print("  music: %d songs, %d notes" % (len(songs), total))


def main():
    os.makedirs(OUT, exist_ok=True)
    for group, entries in GROUPS.items():
        emit(group, entries)
    emit_music()
    print("done — src/art/gen/")


if __name__ == "__main__":
    main()
